### ISSUE TITLE
Secret tests aren't added to the domjudge package

### ISSUE THREAD

**Issue by 2018hahazhufeng** [cn-xcpc-tools/Polygon2DOMjudge#16]
When I using command `/bin/p2d -o ./domjudge.zip ./A` to convert a full problem package (downloaded from Polygon) , the secret tests are not added to the output package. See below pictures for more detail.
![image](https://github.com/cn-xcpc-tools/Polygon2DOMjudge/assets/119911487/76a801de-93dd-41a8-8791-60f1751f3ef9)
![image](https://github.com/cn-xcpc-tools/Polygon2DOMjudge/assets/119911487/693ee6a0-ef50-4502-8ddc-d14728f3d799)

**Comment by cubercsl** [comment]
Could you give me `problem.xml` in polygon package?

Do you have more than one testsets?

**Comment by cubercsl** [comment]
![image](https://github.com/cn-xcpc-tools/Polygon2DOMjudge/assets/22931465/ff89969e-b741-4807-97cc-050c30b810a0)
After investigation, this polygon package has two testsets, which is not supported in current implemention.
